package org.a_cyb.sayitalarm.core.designsystem.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFFB42529)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFFFDAD7)
val light_onPrimaryContainer = Color(0xFF410004)
val light_secondary = Color(0xFF775654)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFFFDAD7)
val light_onSecondaryContainer = Color(0xFF2C1513)
val light_tertiary = Color(0xFF725B2E)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFFFDEA6)
val light_onTertiaryContainer = Color(0xFF271900)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFFFBFF)
val light_onBackground = Color(0xFF201A1A)
val light_surface = Color(0xFFFFFBFF)
val light_onSurface = Color(0xFF201A1A)
val light_surfaceVariant = Color(0xFFF5DDDB)
val light_onSurfaceVariant = Color(0xFF534342)
val light_outline = Color(0xFF857371)
val light_inverseOnSurface = Color(0xFFFBEEEC)
val light_inverseSurface = Color(0xFF362F2E)
val light_inversePrimary = Color(0xFFFFB3AE)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFFB42529)
val light_outlineVariant = Color(0xFFD8C2BF)
val light_scrim = Color(0xFF000000)

val dark_primary = Color(0xFFFFB3AE)
val dark_onPrimary = Color(0xFF68000B)
val dark_primaryContainer = Color(0xFF920415)
val dark_onPrimaryContainer = Color(0xFFFFDAD7)
val dark_secondary = Color(0xFFE7BDB9)
val dark_onSecondary = Color(0xFF442927)
val dark_secondaryContainer = Color(0xFF5D3F3D)
val dark_onSecondaryContainer = Color(0xFFFFDAD7)
val dark_tertiary = Color(0xFFE2C28C)
val dark_onTertiary = Color(0xFF402D04)
val dark_tertiaryContainer = Color(0xFF594319)
val dark_onTertiaryContainer = Color(0xFFFFDEA6)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF201A1A)
val dark_onBackground = Color(0xFFEDE0DE)
val dark_surface = Color(0xFF201A1A)
val dark_onSurface = Color(0xFFEDE0DE)
val dark_surfaceVariant = Color(0xFF534342)
val dark_onSurfaceVariant = Color(0xFFD8C2BF)
val dark_outline = Color(0xFFA08C8A)
val dark_inverseOnSurface = Color(0xFF201A1A)
val dark_inverseSurface = Color(0xFFEDE0DE)
val dark_inversePrimary = Color(0xFFB42529)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFFFFB3AE)
val dark_outlineVariant = Color(0xFF534342)
val dark_scrim = Color(0xFF000000)

//val seed = Color(0xFF900214)
